name: premierWorkflow
on: push

jobs: 
  network-and-system:
    runs-on: ubuntu-latest
    steps:
      - name: information sur la machine
        run: hostnamectl
      - name: adressage ipv4
        run: ip a -4    
      - name: mon identit√© de connexion
        run: who am i
